### ISSUE TITLE
When adding graphics before \question, it will not be added to a question

### ISSUE THREAD

**Issue by lenfra** [lenfra/examtool#10]
Should this one be fixed? Investigate

**Comment by dbosk** [comment]
Usually graphics (figures, tables) should be added *after* the first 
paragraph using it. So in this case I'd say it should be place after the 
question, not before.

So, no need to fix this, I'd say.

**Comment by lenfra** [comment]
I agree, I forgot to add a bit of backstory, this I noticed happened when importing an exam that had the pictures placed not in connection with the question. So I made a notice of it, to see if it was worth looking into later on, or if I should just require that exams that are imported needs to follow a certain structure.
I'm going with the latter:)
